language: minimal

services:
  - docker

env: 
  - DOCKER_COMPOSE_VERSION=1.23.2 

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose 
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose 
  - sudo mv docker-compose /usr/local/bin 
  - docker-compose --version
  #- curl -LO https://storage.googleapis.com/kubernetes-release/release/$
  - pip3 --version
  - python --version 
  - pip install awscli --upgrade --user 
  # Install ekscli
  - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
  - sudo mv /tmp/eksctl /usr/local/bin
  - eksctl version
  # Install aws-iam-authenticator
  # See: https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html)
  - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
  - chmod +x ./aws-iam-authenticator
  - sudo mv aws-iam-authenticator /usr/local/bin
  # Install kubectl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

install:
  - docker-compose -f project/c2-microservices-v1/udacity-c2-deployment/docker/docker-compose-build.yaml build --parallel 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f project/c2-microservices-v1/udacity-c2-deployment/docker/docker-compose-build.yaml push

deploy:
   provider: script
   script: bash ci-scripts/deploy.sh
#  on:
#    branch: master
    