apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
